name: Compress and Push to Release Repo

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#    types:
#      - closed

jobs:
  compress-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Checkout YaTai_Intelligence_Release Repo
        uses: actions/checkout@v2
        with:
          repository: LimLLL/YaTai_Intelligence_Release
          token: ${{secrets.YATAI_INTELLIGENCE_RELEASE}}

      - name: Install zip
        run: sudo apt-get install zip -y

      - name: Zip code
        run: zip -r --password ${{ secrets.ZIP_PASSWORD }} compressed_code.zip .

      - name: Push compressed_code.zip to LimLLL/YaTai_Intelligence_Release Repo
        env:
          REPO_KEY: ${{secrets.YATAI_INTELLIGENCE_RELEASE}}
          USERNAME: github-actions[bot]
        run: |
            mv compressed_code.zip YaTai_Intelligence_Release/
            cd YaTai_Intelligence_Release
            git config --local user.name "github-actions[bot]"
            git config --local user.email "<>"
            git add compressed_code.zip
            git commit -m "Compress and push code"
            git push https://$USERNAME:$REPO_KEY@github.com/LimLLL/YaTai_Intelligence_Release.git


